
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ARROW ASSIGN BREAK CLASS COLON COMMA CONTINUE DEF DENT DIV DIV_ASSIGN DOT ELIF ELSE EQUAL ERROR FALSE FLOAT FOR FROM GREATER_EQUAL GREATER_THAN ID IF IMPORT INDENT INT INT_DIV INT_DIV_ASSIGN LBRACE LBRACKET LOWER_EQUAL LOWER_THAN LPAREN MINUS MINUS_ASSIGN MOD MOD_ASSIGN MULT MULT_ASSIGN NON_EQUAL NOT OR PASS PLUS PLUS_ASSIGN POW POW_ASSIGN RBRACE RBRACKET RETURN RPAREN STRING TRUE WHILEprogram : program global_statementglobal_statement : assignmentassignment : ID POW_ASSIGN expressionexpression : STRINGfunction_definition : DEF ID LPAREN parameter_list RPAREN COLON INDENT function_body DENTprogram : global_statementglobal_statement : function_definitionassignment : ID INT_DIV_ASSIGN expressionexpression : FLOATfunction_statement : assignmentfunction_body : function_body function_statementassignment : ID PLUS_ASSIGN expressionexpression : INTstatement : assignmentfunction_body : function_statementassignment : ID MINUS_ASSIGN expressionexpression : IDstatement : function_definitionparameter_list : assignment : ID MULT_ASSIGN expressionparameter_list : IDassignment : ID DIV_ASSIGN expressionparameter_list : parameter_list COMMA IDassignment : ID MOD_ASSIGN expressionassignment : ID ASSIGN expression'
    
_lr_action_items = {'ID':([0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,33,36,37,38,39,40,41,],[5,5,-6,-2,-7,16,-1,17,17,17,17,17,17,17,17,-17,-3,-4,-9,-13,-8,-12,-16,-20,-22,-24,-25,30,35,5,5,-15,-10,-5,-11,]),'DEF':([0,1,2,3,4,7,17,18,19,20,21,22,23,24,25,26,27,28,40,],[6,6,-6,-2,-7,-1,-17,-3,-4,-9,-13,-8,-12,-16,-20,-22,-24,-25,-5,]),'$end':([1,2,3,4,7,17,18,19,20,21,22,23,24,25,26,27,28,40,],[0,-6,-2,-7,-1,-17,-3,-4,-9,-13,-8,-12,-16,-20,-22,-24,-25,-5,]),'POW_ASSIGN':([5,],[8,]),'INT_DIV_ASSIGN':([5,],[9,]),'PLUS_ASSIGN':([5,],[10,]),'MINUS_ASSIGN':([5,],[11,]),'MULT_ASSIGN':([5,],[12,]),'DIV_ASSIGN':([5,],[13,]),'MOD_ASSIGN':([5,],[14,]),'ASSIGN':([5,],[15,]),'STRING':([8,9,10,11,12,13,14,15,],[19,19,19,19,19,19,19,19,]),'FLOAT':([8,9,10,11,12,13,14,15,],[20,20,20,20,20,20,20,20,]),'INT':([8,9,10,11,12,13,14,15,],[21,21,21,21,21,21,21,21,]),'LPAREN':([16,],[29,]),'DENT':([17,18,19,20,21,22,23,24,25,26,27,28,37,38,39,41,],[-17,-3,-4,-9,-13,-8,-12,-16,-20,-22,-24,-25,40,-15,-10,-11,]),'RPAREN':([29,30,31,35,],[-19,-21,32,-23,]),'COMMA':([29,30,31,35,],[-19,-21,33,-23,]),'COLON':([32,],[34,]),'INDENT':([34,],[36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'global_statement':([0,1,],[2,7,]),'assignment':([0,1,36,37,],[3,3,39,39,]),'function_definition':([0,1,],[4,4,]),'expression':([8,9,10,11,12,13,14,15,],[18,22,23,24,25,26,27,28,]),'parameter_list':([29,],[31,]),'function_body':([36,],[37,]),'function_statement':([36,37,],[38,41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program global_statement','program',2,'p_program_multiple','ProgramRules.py',3),
  ('global_statement -> assignment','global_statement',1,'p_global_statement_assignment','StatementRules.py',3),
  ('assignment -> ID POW_ASSIGN expression','assignment',3,'p_pow_assign_expression','AssignmentRules.py',5),
  ('expression -> STRING','expression',1,'p_string_expression','ExpressionRules.py',5),
  ('function_definition -> DEF ID LPAREN parameter_list RPAREN COLON INDENT function_body DENT','function_definition',9,'p_function_definition','FunctionRules.py',5),
  ('program -> global_statement','program',1,'p_program_single','ProgramRules.py',7),
  ('global_statement -> function_definition','global_statement',1,'p_global_statement_function','StatementRules.py',7),
  ('assignment -> ID INT_DIV_ASSIGN expression','assignment',3,'p_int_div_assign_expression','AssignmentRules.py',9),
  ('expression -> FLOAT','expression',1,'p_float_expression','ExpressionRules.py',9),
  ('function_statement -> assignment','function_statement',1,'p_function_statement_assignment','StatementRules.py',11),
  ('function_body -> function_body function_statement','function_body',2,'p_function_body_multiple','FunctionRules.py',12),
  ('assignment -> ID PLUS_ASSIGN expression','assignment',3,'p_plus_assign_expression','AssignmentRules.py',13),
  ('expression -> INT','expression',1,'p_int_expression','ExpressionRules.py',13),
  ('statement -> assignment','statement',1,'p_statement_assignment','StatementRules.py',15),
  ('function_body -> function_statement','function_body',1,'p_function_body_single','FunctionRules.py',16),
  ('assignment -> ID MINUS_ASSIGN expression','assignment',3,'p_minus_assign_expression','AssignmentRules.py',17),
  ('expression -> ID','expression',1,'p_identifier_expression','ExpressionRules.py',17),
  ('statement -> function_definition','statement',1,'p_statement_function','StatementRules.py',19),
  ('parameter_list -> <empty>','parameter_list',0,'p_parameter_list_empty','FunctionRules.py',20),
  ('assignment -> ID MULT_ASSIGN expression','assignment',3,'p_mult_assign_expression','AssignmentRules.py',21),
  ('parameter_list -> ID','parameter_list',1,'p_parameter_list_single','FunctionRules.py',24),
  ('assignment -> ID DIV_ASSIGN expression','assignment',3,'p_div_assign_expression','AssignmentRules.py',25),
  ('parameter_list -> parameter_list COMMA ID','parameter_list',3,'p_parameter_list_multiple','FunctionRules.py',28),
  ('assignment -> ID MOD_ASSIGN expression','assignment',3,'p_mod_assign_expression','AssignmentRules.py',29),
  ('assignment -> ID ASSIGN expression','assignment',3,'p_assignment','AssignmentRules.py',33),
]
